name: Docker Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: startsWith(github.event.head_commit.message, 'release(server)') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t jxlpzqc/league-of-pride-server:latest .

      - name: Push Docker image to Docker Hub
        run: docker push jxlpzqc/league-of-pride-server:latest
